loader_options:
    clic:
        qf_seq_name: "clic_seq"
        keylist:
            [
                "energy",
                "ECAL",
                "ECAL_E",
                "HCAL",
                "HCAL_E",
                "recoEta",
                "recoPhi",
                "recoTheta",
            ]
        chunksize: 100
        batch_size: 100
        validation_set_size: 5000
        test_set_size: 30000
        prefetch_batches: 2
        num_workers_transform: 15
        num_workers_stack: 1
