tag: default
tensorboard_name: default
loglevel: 1
datasetpath: 'data/clic'
seed: 0
loader:
  xname: "ECAL"
  yname: "energy"
  chunksize: 200
  prefetch_batches: 4
  batch_size : 500
  num_workers: 8
  validation_set_size: 1000
  transform_workers: 20
nlayers: 25
model:
  name: "default"
  n_epochs : 10
  lr : 0.0002
  dyn_features: 10
  static_features: 3
training:
  validation_interval: 50
  early_stopping: 5
  early_stopping_improvement: 0.02