tag: default
loglevel: 1
seed: 0
comet_project_name: "normal"

models:
    gen:
        name: gen_deeptree
        params: ${model_param_options[${models.gen.name}]}
        losses: "${optionlist:${loss_options},${models.gen.losses_list}}"
        # losses_list: [WGenLoss]
        losses_list: [CEGenLoss]
        optim:
            name: Adam
            params: ${optim_options[Adam]}
    disc:
        name: disc_prog
        params: ${model_param_options[${models.disc.name}]}
        losses: "${optionlist:${loss_options},${models.disc.losses_list}}"
        # losses_list: [WDiscLoss,GradientPenalty]
        losses_list: [CEDiscLoss]
        optim:
            name: Adam
            params: ${optim_options[Adam]}

ffn:
    activation: ReLU
    activation_params: {}
    init_weights_bias_const: 0.1
    init_weights: xavier_uniform_


model_param_options:
    gen_treepc:
        features: [96, 64, 64, 64, 64, 64, 4]
        degrees: [2, 2, 2, 2, 2, 64]
        support: 10
    gen_deeptree:
        n_global: 5
        conv_name: AncestorConv
        conv_parem: ${layer_options[${model_param_options.gen_deeptree.conv_name}]}
        branching_param: ${layer_options[BranchingLayer]}
        pp_conv: False
    gen_edgeconv:
        n_layers: 5
        n_features: 2
        n_global: 5
    gen_moons: {}
    disc_clic:
        n_features: ${loader[n_features]}
        n_prop: 20
        n_global: 2
        n_nn: 8
    disc_clicgat: ${model_param_options[disc_clic]}
    disc_graphgym:
        n_features: ${loader[n_features]}
        n_nn: 8
    disc_hlvs: {}
    disc_treepc:
        features: ${tree[features]} # [4, 64, 128, 256]
    disc_pointnet:
        batch_size: ${loader[batch_size]}
        n_points: ${loader[max_points]}
        n_features: ${loader[n_features]}
    disc_prog:
      leveldisc: disc_graphgym
      levelparams: ${model_param_options[disc_graphgym]}


tree:
    branches: [2, 4, 4, 16]
    features: [64,64,32,16,2]


layer_options:
    GINConv: {}
    AncestorConv:
        residual: True
    BranchingLayer:
        residual: True

loss_options:
    WGenLoss:
        factor: 1.0
    WDiscLoss:
        factor: 1.0
    CEDiscLoss:
        factor: 1.0
    CEGenLoss:
        factor: 1.0
    GradientPenalty:
        factor: 1.0
        gamma: 1.0
    mean_dist:
        factor: 1.0
    physics:
        factor: 1.0
    frechetpcdist:
        factor: 1.0
    mmd:
      factor: 1.0
      kernel: "rbf"

optim_options:
    Adam:
        weight_decay: 1.0e-4
        lr: 2.e-4
    SGD:
        lr: 2.e-4
    FakeOptimizer: {}

training:
    events_processed_before_validation: 100000
    disc_steps_per_gen_step: 5
    early_stopping:
        validation_steps: 100
        improvement: 0.02
    checkpoint_minutes: 30
validation:
    interval: "${div:${training.events_processed_before_validation},${loader.batch_size}}"
    stop_key: stop_key
    metrics:
        hlv_w1:
            factor: 1.0
            wgrad: False
            foreach_hlv: True
testing:
    n_events: 2000

path:
    dataset: "${loader.dataset_path}"
    # dataset: "data/hgcal_william"
    dataset_glob: "**/*.root"
    dataset_processed: "${path.dataset}/pkl_${loader_name}_${loader_hash}"
    ds_lenghts: "${path.dataset_processed}/filelengths.yaml"
    validation: "${path.dataset_processed}/validation.pt"
    test: "${path.dataset_processed}/test.pt"
    training: "${path.dataset_processed}/training"
    training_glob: "*.pt"
    geo_lup: "data/geo_hgcal/DetIdLUT.root"
    run_path: "wd/${tag}/${hash}"
    full_config: "${path.run_path}/full_config.yaml"
    tensorboard: "${path.run_path}/tb"
    checkpoint: "${path.run_path}/checkpoint.torch"
    checkpoint_old: "${path.run_path}/checkpoint_old.torch"
    state: "${path.run_path}/state.yaml"
    state_old: "${path.run_path}/state_old.yaml"
    comet_exp_key: "${path.run_path}/comet_experiment_key"


loader: "${merge:${loader_options[default]},${loader_options[${loader_name}]}}"
loader_name: normal

loader_options:
    default:
        rootprefix: "treeMaker/tree"
        preprocess_training: True
        debug: False
        chunksize: 100
        batch_size: 50
        validation_set_size: 5000
        test_set_size: 5000
        events_per_file: 100000
        prefetch_batches: 5
        num_workers_transform: 30
        num_workers_stack: 1
        num_workers_postprocess: 1
    hgcal:
        # cell_prop_keys: ["x", "y", "z", "celltype", "issilicon"]
        batch_size: 100
        max_points: 4085
        dataset_path: "data/hgcal_william"
        braches:
            id: "simHit_detid"
            energy: "genPh_E"
            hit_energy: "simHit_E"
        cell_prop_keys: ["E","x", "y", "z"]
        n_features: 4
    pcgraph: ${loader_options[hgcal]}
    puregraph: ${loader_options[hgcal]}
    normal:
        dataset_path: "data/normal"
        cell_prop_keys: ["x", "y"]
        n_features: 2
        max_points: 512
    moons:
        dataset_path: "data/moons"
        cell_prop_keys: ["x", "y"]
        n_features: 2
        max_points: 512
        cluster_tree: false
        cluster_method: "random"
        chunksize: 1000
        batch_size: 500
