tag: default
tensorboard_name: default
loglevel: 1
path:
  dataset: 'data/clic'
  validation: 'data/clic_valtest/validation.torch'
  test: 'data/clic_valtest/test.torch'
seed: 0
loader:
  xname: "ECAL"
  yname: "energy"
  chunksize: 200
  prefetch_batches: 4
  batch_size : 100
  num_workers: 8
  validation_set_size: 1000
  test_set_size: 6000
  transform_workers: 20
nlayers: 25
model:
  name: "default"
  n_epochs : 10
  dyn_features: 10
  static_features: 3
training:
  validation_interval: 50
  early_stopping: 7
  early_stopping_improvement: 0.02
loss: 
  name: MSELoss
optimizer:
  name: Adam
  parameters:
    weight_decay: 0.00001
    lr : 0.0002
