tag: default
loglevel: 1
path:
  log: "wd/${tag}/log"
  dataset: 'data/clic'
  validation: 'data/clic_valtest/validation.torch'
  test: 'data/clic_valtest/test.torch'
  train_config: "wd/${tag}/resulting_train_config.yaml"
  tensorboard: "runs/${tag}"
  state: "wd/${tag}/state.yaml"
  state_old: "wd/${tag}/state_old.yaml"
  checkpoint: "wd/${tag}/checkpoint.torch"
  checkpoint_old: "wd/${tag}/checkpoint_old.torch"
  best_model: "wd/${tag}/best_model.torch"
  predict_csv: "wd/${tag}/prediction.csv"
seed: 0
loader:
  xname: "ECAL"
  yname: "energy"
  chunksize: 200
  prefetch_batches: 4
  batch_size : 100
  num_workers: 8
  validation_set_size: 1000
  test_set_size: 6000
  transform_workers: 20
nlayers: 25
model:
  name: "default"
  n_epochs : 10
  dyn_features: 10
  static_features: 3
training:
  validation_interval: 50
  checkpoint_interval: 50
  early_stopping: 7
  early_stopping_improvement: 0.02
loss: 
  name: MSELoss
optimizer:
  name: Adam
  parameters: ${loss_params[${optimizer.name}]}

loss_params:
  Adam:
    weight_decay: 0.0001
    lr : 0.0002
  SGD:
    lr : 0.0002
