tag: default
loglevel: 1
seed: 0

models:
    gen:
        name: gen_treepc
        param:
            features: [96, 64, 64, 64, 64, 64, 4]
            degrees: [2, 2, 2, 2, 2, 64]
            support: 10
        losses:
            WGenLoss: ${loss_options[WGenLoss]}
            mean_dist: ${loss_options[WGenLoss]}
        optim:
            name: Adam
            params: ${optim_options[Adam]}
    disc:
        name: disc_treepc
        param:
            features: [4, 64, 128, 256, 512, 1024]
        losses:
            WDiscLoss: ${loss_options[WDiscLoss]}
            GradientPenalty: ${loss_options[GradientPenalty]}
        optim:
            name: Adam
            params: ${optim_options[Adam]}

optim_options:
    Adam:
        weight_decay: 0.0001
        lr: 0.0002
    SGD:
        lr: 0.0002


loss_options:
    WGenLoss:
        factor: 1.0
    WDiscLoss:
        factor: 1.0
    GradientPenalty:
        factor: 1.0
        gamma: 1.0
    mean_dist:
        factor: 1.0
    frechetpcdist:
        factor: 1.0


training:
    events_processed_before_validation: 100000
    validation_interval: "${div:${training.events_processed_before_validation},${loader.batch_size}}"
    val_loss:
        w1_energy_sum:
            factor: 1.0
            function_file: hlv_w1
            var: energy_sum
            wgrad: False
        w1_energy_sum_std:
            factor: 1.0
            function_file: hlv_w1
            var: energy_sum_std
            wgrad: False
        w1_x_mean:
            factor: 1.0
            function_file: hlv_w1
            var: x_mean
            wgrad: False
        w1_x_std:
            factor: 1.0
            function_file: hlv_w1
            var: x_std
            wgrad: False
        w1_x_mom3:
            factor: 1.0
            function_file: hlv_w1
            var: x_mom3
            wgrad: False
        w1_x_mom4:
            factor: 1.0
            function_file: hlv_w1
            var: x_mom4
            wgrad: False
        w1_x_mean_ew:
            factor: 1.0
            function_file: hlv_w1
            var: x_mean_ew
            wgrad: False
        w1_x_std_ew:
            factor: 1.0
            function_file: hlv_w1
            var: x_std_ew
            wgrad: False
        w1_x_mom3_ew:
            factor: 1.0
            function_file: hlv_w1
            var: x_mom3_ew
            wgrad: False
        w1_x_mom4_ew:
            factor: 1.0
            function_file: hlv_w1
            var: x_mom4_ew
            wgrad: False
        w1_y_mean:
            factor: 1.0
            function_file: hlv_w1
            var: y_mean
            wgrad: False
        w1_y_std:
            factor: 1.0
            function_file: hlv_w1
            var: y_std
            wgrad: False
        w1_y_mom3:
            factor: 1.0
            function_file: hlv_w1
            var: y_mom3
            wgrad: False
        w1_y_mom4:
            factor: 1.0
            function_file: hlv_w1
            var: y_mom4
            wgrad: False
        w1_y_mean_ew:
            factor: 1.0
            function_file: hlv_w1
            var: y_mean_ew
            wgrad: False
        w1_y_std_ew:
            factor: 1.0
            function_file: hlv_w1
            var: y_std_ew
            wgrad: False
        w1_y_mom3_ew:
            factor: 1.0
            function_file: hlv_w1
            var: y_mom3_ew
            wgrad: False
        w1_y_mom4_ew:
            factor: 1.0
            function_file: hlv_w1
            var: y_mom4_ew
            wgrad: False
        w1_z_mean:
            factor: 1.0
            function_file: hlv_w1
            var: z_mean
            wgrad: False
        w1_z_std:
            factor: 1.0
            function_file: hlv_w1
            var: z_std
            wgrad: False
        w1_z_mom3:
            factor: 1.0
            function_file: hlv_w1
            var: z_mom3
            wgrad: False
        w1_z_mom4:
            factor: 1.0
            function_file: hlv_w1
            var: z_mom4
            wgrad: False
        w1_z_mean_ew:
            factor: 1.0
            function_file: hlv_w1
            var: z_mean_ew
            wgrad: False
        w1_z_std_ew:
            factor: 1.0
            function_file: hlv_w1
            var: z_std_ew
            wgrad: False
        w1_z_mom3_ew:
            factor: 1.0
            function_file: hlv_w1
            var: z_mom3_ew
            wgrad: False
        w1_z_mom4_ew:
            factor: 1.0
            function_file: hlv_w1
            var: z_mom4_ew
            wgrad: False
    disc_steps_per_gen_step: 10
    early_stopping:
        validation_steps: 40
        improvement: 0.02

path:
    dataset: "data/hgcal_william"
    dataset_glob: "**/*.root"
    dataset_processed: "${path.dataset}/pkl_${loader_name}_${loader_hash}"
    ds_lenghts: "${path.dataset_processed}/filelengths.yaml"
    validation: "${path.dataset_processed}/validation.pt"
    test: "${path.dataset_processed}/test.pt"
    training: "${path.dataset_processed}/training"
    training_glob: "*.pt"
    geo_lup: "data/geo_hgcal/DetIdLUT.root"
    run_path: "wd/${tag}/${hash}"
    train_config: "${path.run_path}/resulting_train_config.yaml"
    full_config: "${path.run_path}/full_config.yaml"
    tensorboard: "${path.run_path}/tb"
    checkpoint: "${path.run_path}/checkpoint.torch"
    checkpoint_old: "${path.run_path}/checkpoint_old.torch"
    state: "${path.run_path}/state.torch"
    state_old: "${path.run_path}/state_old.torch"
    predict_csv: "${path.run_path}/prediction.csv"
    comet_exp_key: "${path.run_path}/comet_experiment_key"
    log: "${path.run_path}/${command}.log"
    loader_log: "${path.run_path}/${command}_loader.log"

loader: ${loader_options[${loader_name}]}
loader_name: hgcal
loader_options:
    clic:
        qf_seq_name: "clic_seq"
        keylist:
            [
                "energy",
                "ECAL",
                "ECAL_E",
                "HCAL",
                "HCAL_E",
                "recoEta",
                "recoPhi",
                "recoTheta",
            ]
        chunksize: 100
        batch_size: 100
        validation_set_size: 5000
        test_set_size: 30000
        prefetch_batches: 2
        num_workers_transform: 15
        num_workers_stack: 1
    hgcal:
        qf_seq_name: "hgcal_seq"
        rootprefix: "treeMaker/tree"
        preprocess_training: True
        debug: False
        keylist: ["genPh_E", "simHit_detid", "simHit_E"]
        hlvs:
            [
                "sum_energy",
                "num_isolated",
                "isolated_energy",
                "isolated_E_fraction",
                "x_mean",
                "x_std",
                "x_mom3",
                "y_mean",
                "y_std",
                "y_mom3",
                "z_mean",
                "z_std",
                "z_mom3",
            ]
        cell_prop_keys: ["x", "y", "z", "celltype", "issilicon"]
        braches:
            id: "simHit_detid"
            energy: "genPh_E"
            hit_energy: "simHit_E"
        chunksize: 100
        batch_size: 100
        validation_set_size: 5000
        test_set_size: 30000
        prefetch_batches: 2
        num_workers_transform: 30
        num_workers_stack: 1
    pc:
        qf_seq_name: "pc_seq"
        rootprefix: "treeMaker/tree"
        preprocess_training: False
        debug: False
        braches:
            id: "simHit_detid"
            energy: "genPh_E"
            hit_energy: "simHit_E"
        keylist: ["genPh_E", "simHit_detid", "simHit_E"]
        cell_prop_keys: ["x", "y", "z"]
        chunksize: 100
        batch_size: 100
        validation_set_size: 5000
        test_set_size: 30000
        prefetch_batches: 2
        num_workers_transform: 10
        num_workers_stack: 1
        num_workers_postprocess: 5
