tag: default
loglevel: 1
path:
  dataset: 'data/clic'
  validation: 'data/clic_valtest/validation.torch'
  test: 'data/clic_valtest/test.torch'
  run_path: 'wd/${tag}/${hash}'
  comet_exp_key: "${path.run_path}/comet_experiment_key"
  log: "${path.run_path}/log"
  train_config: "${path.run_path}/resulting_train_config.yaml"
  full_config: "${path.run_path}/full_config.yaml"
  tensorboard: "runs/${tag}/${hash}"
  state: "${path.run_path}/state.yaml"
  state_old: "${path.run_path}/state_old.yaml"
  checkpoint: "${path.run_path}/checkpoint.torch"
  checkpoint_old: "${path.run_path}/checkpoint_old.torch"
  best_model: "${path.run_path}/best_model.torch"
  predict_csv: "${path.run_path}/prediction.csv"
seed: 0
loader:
  keylist: [
    "energy",
    "ECAL",
    "ECAL_E",
    "HCAL",
    "HCAL_E",
    "recoEta",
    "recoPhi",
    "recoTheta",
  ]
  chunksize: 200
  prefetch_batches: 4
  batch_size : 10
  num_workers_transform: 6
  num_workers_stack: 9
  validation_set_size: 1000
  test_set_size: 6000
  transform_workers: 15
nlayers: 25
model:
  name: "default"
  n_epochs : 10
  dyn_features: 10
  static_features: 3
training:
  events_processed_before_validation: 6000
  validation_interval: '${div:${training.events_processed_before_validation},${loader.batch_size}}'
  checkpoint_interval: 50
  early_stopping: 7
  early_stopping_improvement: 0.02
yvar : "energy"
loss:
  name: MSELoss
optimizer:
  name: Adam
  parameters: ${loss_params[${optimizer.name}]}

loss_params:
  Adam:
    weight_decay: 0.0001
    lr : 0.0002
  SGD:
    lr : 0.0002
