tag: default
loglevel: 1
seed: 0
comet_project_name: "gan"

models:
    gen:
        name: gen_treepc
        param: ${model_param_options[${models.gen.name}]}
        losses: "${optionlist:${loss_options},[WGenLoss,mean_dist,physics]}"
        optim:
            name: Adam
            params: ${optim_options[Adam]}
    disc:
        name: disc_treepc
        param: ${model_param_options[${models.disc.name}]}
        losses: "${optionlist:${loss_options},[WDiscLoss,GradientPenalty]}"
        optim:
            name: Adam
            params: ${optim_options[Adam]}

model_param_options:
    gen_treepc:
        features: [96, 64, 64, 64, 64, 64, 4]
        degrees: [2, 2, 2, 2, 2, 64]
        support: 10
    gen_deeptree_pc:
        n_hidden_features: 4
        n_global: 6
        n_branches: 2
        n_levels: 12
        n_events: "${loader.batch_size}"
        post_gen_mp_steps: 10
    disc_treepc:
        features: [4, 64, 128, 256, 512, 1024]

loss_options:
    WGenLoss:
        factor: 1.0
    WDiscLoss:
        factor: 1.0
    CEDiscLoss:
        factor: 1.0
    CEGenLoss:
        factor: 1.0
    GradientPenalty:
        factor: 1.0
        gamma: 1.0
    mean_dist:
        factor: 1.0
    physics:
        factor: 100.0
    frechetpcdist:
        factor: 1.0

optim_options:
    Adam:
        weight_decay: 0.0001
        lr: 0.0002
    SGD:
        lr: 0.0002

training:
    events_processed_before_validation: 100000
    disc_steps_per_gen_step: 10
    early_stopping:
        validation_steps: 15
        improvement: 0.02
validation:
    interval: "${div:${training.events_processed_before_validation},${loader.batch_size}}"
    stop_key: stop_key
    metrics:
        hlv_w1:
            factor: 1.0
            function_file: hlv_w1
            wgrad: False
            foreach_hlv: True
testing:
    n_events: 2000

path:
    dataset: "data/hgcal_william"
    dataset_glob: "**/*.root"
    dataset_processed: "${path.dataset}/pkl_${loader_name}_${loader_hash}"
    ds_lenghts: "${path.dataset_processed}/filelengths.yaml"
    validation: "${path.dataset_processed}/validation.pt"
    test: "${path.dataset_processed}/test.pt"
    training: "${path.dataset_processed}/training"
    training_glob: "*.pt"
    geo_lup: "data/geo_hgcal/DetIdLUT.root"
    run_path: "wd/${tag}/${hash}"
    train_config: "${path.run_path}/resulting_train_config.yaml"
    full_config: "${path.run_path}/full_config.yaml"
    tensorboard: "${path.run_path}/tb"
    checkpoint: "${path.run_path}/checkpoint.torch"
    checkpoint_old: "${path.run_path}/checkpoint_old.torch"
    state: "${path.run_path}/state.torch"
    state_old: "${path.run_path}/state_old.torch"
    comet_exp_key: "${path.run_path}/comet_experiment_key"
    log: "${path.run_path}/${command}.log"
    loader_log: "${path.run_path}/${command}_loader.log"

loader: ${loader_options[${loader_name}]}
loader_name: pc

loader_options:
    hgcal:
        qf_seq_name: "hgcal_seq"
        rootprefix: "treeMaker/tree"
        preprocess_training: True
        debug: False
        hlvs:
            [
                "sum_energy",
                "num_isolated",
                "isolated_energy",
                "isolated_E_fraction",
                "x_mean",
                "x_std",
                "x_mom3",
                "y_mean",
                "y_std",
                "y_mom3",
                "z_mean",
                "z_std",
                "z_mom3",
            ]
        cell_prop_keys: ["x", "y", "z", "celltype", "issilicon"]
        braches:
            id: "simHit_detid"
            energy: "genPh_E"
            hit_energy: "simHit_E"
        chunksize: 100
        batch_size: 100
        validation_set_size: 5000
        test_set_size: 30000
        prefetch_batches: 2
        num_workers_transform: 30
        num_workers_stack: 1
    pc:
        qf_seq_name: "pc_seq"
        rootprefix: "treeMaker/tree"
        preprocess_training: True
        debug: False
        braches:
            id: "simHit_detid"
            energy: "genPh_E"
            hit_energy: "simHit_E"
        cell_prop_keys: ["x", "y", "z"]
        max_points: 4085
        n_features: 4
        chunksize: 100
        batch_size: 100
        validation_set_size: 5000
        test_set_size: 30000
        prefetch_batches: 2
        num_workers_transform: 10
        num_workers_stack: 1
        num_workers_postprocess: 5
